### ISSUE TITLE
bloquote p non visible en thème clair

### ISSUE THREAD

**Issue by thomasbnt** [Grafikart/Grafikart.fr#470]
Comme on peut le voir ici, le texte n'est pas visible en thème clair dans un `<blockquote>` : 

![Preview blockquote](https://user-images.githubusercontent.com/14293805/221371382-52ad5ebc-e800-4aef-9024-b1c26a03ddfc.png)

_Vu sur https://grafikart.fr/blog/metier-dev-freelance_

```css
.blog-single__body.text-only p:first-child {
    color: var(--color-inversed);
    margin-bottom: 70px;
}
```
